import PDFDocument from "pdfkit";
import {
  type CvData,
  type CvExperience,
  type CvEducation,
  C,
  FONT_BOLD,
  FONT_REGULAR,
  PAGE_MARGIN,
  CONTENT_WIDTH,
} from "./cv-types.js";

export type { CvData, CvExperience, CvEducation };

const drawDivider = (doc: PDFKit.PDFDocument, y: number) => {
  doc
    .moveTo(PAGE_MARGIN, y)
    .lineTo(PAGE_MARGIN + CONTENT_WIDTH, y)
    .lineWidth(0.5)
    .strokeColor(C.divider)
    .stroke();
};

const drawSectionHeader = (doc: PDFKit.PDFDocument, title: string) => {
  doc.moveDown(0.5);
  drawDivider(doc, doc.y);
  doc.moveDown(0.5);
  doc
    .font(FONT_BOLD)
    .fontSize(9)
    .fillColor(C.brand)
    .text(title.toUpperCase(), { characterSpacing: 1.5 });
  doc.moveDown(0.3);
};

const drawHeader = (doc: PDFKit.PDFDocument, data: CvData) => {
  doc
    .font(FONT_BOLD)
    .fontSize(24)
    .fillColor(C.black)
    .text(data.fullName || "Your Name");

  doc.moveDown(0.2);
  doc.font(FONT_REGULAR).fontSize(10).fillColor(C.gray);

  const contactParts = [
    data.email,
    data.phone,
    data.gender,
    data.birthDate,
    data.address,
  ].filter(Boolean);

  doc.text(contactParts.join("  ·  "));

  if (data.portfolioUrl) {
    doc.moveDown(0.2);
    doc
      .font(FONT_REGULAR)
      .fontSize(10)
      .fillColor(C.brand)
      .text(data.portfolioUrl);
  }
};

const drawSummary = (doc: PDFKit.PDFDocument, summary?: string) => {
  if (!summary) return;
  drawSectionHeader(doc, "Summary");
  doc
    .font(FONT_REGULAR)
    .fontSize(10)
    .fillColor(C.black)
    .text(summary, { lineGap: 3 });
};

const drawExperience = (
  doc: PDFKit.PDFDocument,
  experiences: CvExperience[],
) => {
  if (!experiences.length) return;
  drawSectionHeader(doc, "Experience");
  experiences.forEach((exp, i) => {
    const period = exp.endYear
      ? `${exp.startYear} – ${exp.endYear}`
      : `${exp.startYear} – Present`;

    doc.font(FONT_BOLD).fontSize(11).fillColor(C.black).text(exp.position);

    doc
      .font(FONT_REGULAR)
      .fontSize(10)
      .fillColor(C.gray)
      .text(`${exp.company}  ·  ${period}`);

    if (exp.description) {
      doc.moveDown(0.2);
      doc
        .font(FONT_REGULAR)
        .fontSize(10)
        .fillColor(C.black)
        .text(exp.description, { lineGap: 3 });
    }
    if (i < experiences.length - 1) doc.moveDown(0.6);
  });
};

const drawEducation = (doc: PDFKit.PDFDocument, educations: CvEducation[]) => {
  if (!educations.length) return;
  drawSectionHeader(doc, "Education");

  educations.forEach((edu, i) => {
    const period = edu.endYear
      ? `${edu.startYear} – ${edu.endYear}`
      : `${edu.startYear} – Present`;

    doc.font(FONT_BOLD).fontSize(11).fillColor(C.black).text(edu.institution);

    const degreeText = edu.gpa
      ? `${edu.degree} · ${edu.major}  ·  GPA ${edu.gpa}`
      : `${edu.degree} · ${edu.major}`;

    doc
      .font(FONT_REGULAR)
      .fontSize(10)
      .fillColor(C.gray)
      .text(`${degreeText}  ·  ${period}`);

    if (i < educations.length - 1) doc.moveDown(0.6);
  });
};

const drawSkills = (
  doc: PDFKit.PDFDocument,
  verifiedSkills: string[],
  additionalSkills: string[],
) => {
  const allSkills = [...verifiedSkills, ...additionalSkills];
  if (!allSkills.length) return;

  drawSectionHeader(doc, "Skills");

  if (verifiedSkills.length) {
    doc
      .font(FONT_BOLD)
      .fontSize(9)
      .fillColor(C.brand)
      .text("Verified by Lokerin", { characterSpacing: 0.5 });
    doc.moveDown(0.2);
    doc
      .font(FONT_REGULAR)
      .fontSize(10)
      .fillColor(C.black)
      .text(verifiedSkills.join("  ·  "), { lineGap: 3 });
    doc.moveDown(0.4);
  }

  if (additionalSkills.length) {
    doc
      .font(FONT_REGULAR)
      .fontSize(10)
      .fillColor(C.black)
      .text(additionalSkills.join("  ·  "), { lineGap: 3 });
  }
};

export const buildCvPdf = async (data: CvData): Promise<Buffer> => {
  const doc = new PDFDocument({
    size: "A4",
    margin: PAGE_MARGIN,
  });

  const chunks: Buffer[] = [];
  doc.on("data", (c) => chunks.push(c));

  drawHeader(doc, data);

  drawSummary(doc, data.summary);
  drawExperience(doc, data.experiences);
  drawEducation(doc, data.educations);
  drawSkills(doc, data.verifiedSkills, data.additionalSkills);

  doc.moveDown(1);
  drawDivider(doc, doc.y);
  doc.moveDown(0.3);
  doc
    .font(FONT_REGULAR)
    .fontSize(8)
    .fillColor(C.lightGray)
    .text("Generated by Lokerin · lokerin.com", { align: "center" });

  doc.end();

  return await new Promise((resolve) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
  });
};
